// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-VhttSi7Cz8BgX1qx0-Th7pASFFoCy8',
    appId: '1:997603782373:web:57672d73d1eb1450a42e0c',
    messagingSenderId: '997603782373',
    projectId: 'disastermain-66982',
    authDomain: 'disastermain-66982.firebaseapp.com',
    storageBucket: 'disastermain-66982.appspot.com',
    measurementId: 'G-T7JRJFPL5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNP7_XsKMJZfNSYiUwZ0AEi35laqosqY',
    appId: '1:997603782373:android:8f9f9ce70d81b4dba42e0c',
    messagingSenderId: '997603782373',
    projectId: 'disastermain-66982',
    storageBucket: 'disastermain-66982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-75pC8_Uo4zYFyaSJ5XLYtuG_8ieH7Pc',
    appId: '1:997603782373:ios:729a9554f6137181a42e0c',
    messagingSenderId: '997603782373',
    projectId: 'disastermain-66982',
    storageBucket: 'disastermain-66982.appspot.com',
    iosBundleId: 'com.example.rain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-75pC8_Uo4zYFyaSJ5XLYtuG_8ieH7Pc',
    appId: '1:997603782373:ios:729a9554f6137181a42e0c',
    messagingSenderId: '997603782373',
    projectId: 'disastermain-66982',
    storageBucket: 'disastermain-66982.appspot.com',
    iosBundleId: 'com.example.rain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX-VhttSi7Cz8BgX1qx0-Th7pASFFoCy8',
    appId: '1:997603782373:web:2d8020df78d3bf5da42e0c',
    messagingSenderId: '997603782373',
    projectId: 'disastermain-66982',
    authDomain: 'disastermain-66982.firebaseapp.com',
    storageBucket: 'disastermain-66982.appspot.com',
    measurementId: 'G-9WV966ESEK',
  );
}
