// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT80-UCvLvEbegp9FEpc0TUpLDtfkFfS8',
    appId: '1:972415762413:web:a0495fc100a6fdda27f1e4',
    messagingSenderId: '972415762413',
    projectId: 'disastermanagement-3c133',
    authDomain: 'disastermanagement-3c133.firebaseapp.com',
    storageBucket: 'disastermanagement-3c133.appspot.com',
    measurementId: 'G-T9SP3QFRNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoZYAso92vKmyur2XzxfpE9-7zoAWmxg',
    appId: '1:972415762413:android:7d7fd5ebba805caa27f1e4',
    messagingSenderId: '972415762413',
    projectId: 'disastermanagement-3c133',
    storageBucket: 'disastermanagement-3c133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkcP9_qEsvjmrHOLWn9TcaRg4LpWW_v5U',
    appId: '1:972415762413:ios:03f836e9e951005127f1e4',
    messagingSenderId: '972415762413',
    projectId: 'disastermanagement-3c133',
    storageBucket: 'disastermanagement-3c133.appspot.com',
    iosBundleId: 'com.example.disasterManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkcP9_qEsvjmrHOLWn9TcaRg4LpWW_v5U',
    appId: '1:972415762413:ios:03f836e9e951005127f1e4',
    messagingSenderId: '972415762413',
    projectId: 'disastermanagement-3c133',
    storageBucket: 'disastermanagement-3c133.appspot.com',
    iosBundleId: 'com.example.disasterManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT80-UCvLvEbegp9FEpc0TUpLDtfkFfS8',
    appId: '1:972415762413:web:b741eab9529b51fc27f1e4',
    messagingSenderId: '972415762413',
    projectId: 'disastermanagement-3c133',
    authDomain: 'disastermanagement-3c133.firebaseapp.com',
    storageBucket: 'disastermanagement-3c133.appspot.com',
    measurementId: 'G-TZJPKFVB94',
  );
}
